import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Sparkles, KeyRound, Mail, ArrowRight, ShieldCheck, MessageCircle, AlertCircle } from 'lucide-react';
import { useMerchantAuth } from '../../context/MerchantAuthContext';

export const MerchantLogin: React.FC = () => {
  const [email, setEmail] = useState('');
  const [pin, setPin] = useState('');
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const { login } = useMerchantAuth();
  const navigate = useNavigate();

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setErrorMessage(null);

    const res = await login(email, pin);
    setLoading(false);

    if (res.success) {
      navigate('/merchant/dashboard');
    } else {
      setErrorMessage(res.error || 'Login failed. Please check your credentials.');
    }
  };

  return (
    <div className="min-h-screen bg-surface-bg flex flex-col justify-center py-12 sm:px-6 lg:px-8">
      <div className="sm:mx-auto sm:w-full sm:max-w-md text-center">
        {/* Logo */}
        <div className="mx-auto w-14 h-14 rounded-2xl bg-teal-brand flex items-center justify-center text-white shadow-xl shadow-teal-brand/20">
          <Sparkles className="w-8 h-8 text-coral-brand" />
        </div>
        <h2 className="mt-4 text-2xl font-extrabold text-slate-900 tracking-tight">
          Merchant Login
        </h2>
        <p className="mt-1 text-xs text-slate-500">
          Sign in with your Email and Admin-provided secure PIN
        </p>
      </div>

      <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md px-4">
        <div className="bg-white py-8 px-6 shadow-card rounded-2xl border border-slate-200 sm:px-10 space-y-6">

          {errorMessage && (
            <div className="p-3.5 bg-red-50 border border-red-200 text-red-700 rounded-xl text-xs flex items-start gap-2.5">
              <AlertCircle className="w-4 h-4 shrink-0 text-red-500 mt-0.5" />
              <span>{errorMessage}</span>
            </div>
          )}

          <form onSubmit={handleLogin} className="space-y-4">
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Merchant Email Address
              </label>
              <div className="relative">
                <input
                  type="email"
                  required
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="name@yourshop.com"
                  className="w-full pl-9 pr-3 py-2.5 text-xs border border-slate-300 rounded-xl focus:ring-2 focus:ring-teal-brand/30 focus:border-teal-brand outline-none text-slate-900 font-medium"
                />
                <Mail className="w-4 h-4 text-slate-400 absolute left-3 top-3" />
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Admin-Provisioned Login PIN
              </label>
              <div className="relative">
                <input
                  type="password"
                  required
                  value={pin}
                  onChange={(e) => setPin(e.target.value)}
                  placeholder="Enter 6-digit PIN"
                  className="w-full pl-9 pr-3 py-2.5 text-xs border border-slate-300 rounded-xl focus:ring-2 focus:ring-teal-brand/30 focus:border-teal-brand outline-none text-slate-900 font-mono font-bold tracking-widest"
                />
                <KeyRound className="w-4 h-4 text-slate-400 absolute left-3 top-3" />
              </div>
              <p className="text-[11px] text-slate-400 mt-1">
                Your PIN was generated by the Won More Admin upon WhatsApp onboarding.
              </p>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full flex items-center justify-center gap-2 py-3 bg-coral-brand hover:bg-coral-hover text-white text-xs font-bold rounded-xl shadow-md shadow-coral-brand/20 transition disabled:opacity-50"
            >
              <span>{loading ? 'Authenticating...' : 'Sign In to Merchant Dashboard'}</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </form>

          {/* WhatsApp Support Notice */}
          <div className="pt-4 border-t border-slate-100 text-center">
            <p className="text-xs text-slate-500">
              Need to create a new shop account or forgot your PIN?
            </p>
            <a
              href="https://wa.me/15551234567?text=Hello%20Won%20More!%20I%20want%20to%20subscribe%20my%20shop%20to%20Scratch%20%26%20Win."
              target="_blank"
              rel="noopener noreferrer"
              className="mt-2 inline-flex items-center gap-1.5 text-xs font-bold text-emerald-700 hover:text-emerald-800"
            >
              <MessageCircle className="w-3.5 h-3.5" />
              <span>Contact Admin on WhatsApp</span>
            </a>
          </div>

        </div>
      </div>
    </div>
  );
};
